/** A Higher Secondary lab as the GradeNext catalogue sees it. */
export interface HsLab {
  /** The Smart Lab engine's own id: smartlab/index.html#<id> opens it. */
  id: string;
  subject: "physics" | "chemistry" | "biology";
  /** The NCERT class whose chapter this lab serves. */
  ncertClass: 11 | 12;
  chapter: string;
  name: string;
  exams: string[];
  /** Exam weight as the lab itself states it. */
  weight: string;
}

export const HS_SUBJECT_LABEL: Record<HsLab["subject"], string> = {
  physics: "Physics",
  chemistry: "Chemistry",
  biology: "Biology",
};

/**
 * The Higher Secondary suite — every InsightVis lab, merged into GradeNext.
 *
 * These run on the Smart Lab engine in the repository-root smartlab/ folder,
 * not on the React sim engine, so this list is their catalogue entry: the
 * order is the engine's own rail order (subject, then chapter, then lab), and
 * the ids are the engine's. hsLabs.test.ts reads the lab sources and fails if
 * this list and the engine ever disagree, so a lab cannot be added to one and
 * forgotten in the other.
 *
 * ncertClass is the NCERT class whose chapter the lab serves; every lab is
 * still offered to both Class 11 and Class 12 students.
 */
export const HS_LABS: HsLab[] = [
  { id: "lorentz", subject: "physics", ncertClass: 12,
    chapter: "Moving Charges & Magnetism",
    name: "The Lorentz Force Bench — Five Experiments, One Equation",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "ydse", subject: "physics", ncertClass: 12,
    chapter: "Wave Optics",
    name: "Young's Double Slit — Path Difference to Fringe",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "cyclotron", subject: "physics", ncertClass: 12,
    chapter: "Moving Charges & Magnetism",
    name: "The Cyclotron — Resonance and Maximum Energy",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "resolving", subject: "physics", ncertClass: 12,
    chapter: "Wave Optics",
    name: "Diffraction & Resolving Power — the Rayleigh Criterion",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "rolling", subject: "physics", ncertClass: 11,
    chapter: "System of Particles & Rotational Motion",
    name: "Rolling, Slipping and the Moment of Inertia",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "resonance", subject: "physics", ncertClass: 11,
    chapter: "Oscillations",
    name: "Resonance, Damping and Normal Modes",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "gauss", subject: "physics", ncertClass: 12,
    chapter: "Electric Charges & Fields",
    name: "Electric Field, Potential and Gauss's Law",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "lcr", subject: "physics", ncertClass: 12,
    chapter: "Alternating Current",
    name: "Series LCR — Phasors, Resonance and Power Factor",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "photoelectric", subject: "physics", ncertClass: 12,
    chapter: "Dual Nature of Radiation & Matter",
    name: "The Photoelectric Effect and Matter Waves",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "kinetic", subject: "physics", ncertClass: 11,
    chapter: "Kinetic Theory of Gases",
    name: "Kinetic Theory — Where the Maxwell Curve Comes From",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "induction", subject: "physics", ncertClass: 12,
    chapter: "Electromagnetic Induction",
    name: "Electromagnetic Induction — Lenz's Law, Measured",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "heatengine", subject: "physics", ncertClass: 11,
    chapter: "Thermodynamics",
    name: "Heat Engines — the PV Cycle and the Carnot Limit",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "circuits", subject: "physics", ncertClass: 12,
    chapter: "Current Electricity",
    name: "The Circuit Bench — Kirchhoff, Wheatstone and the Potentiometer",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "rayoptics", subject: "physics", ncertClass: 12,
    chapter: "Ray Optics & Optical Instruments",
    name: "The Optical Bench — Lenses, Mirrors and Real Images",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "waves", subject: "physics", ncertClass: 11,
    chapter: "Waves",
    name: "Waves and Sound — Standing Waves, Beats and Doppler",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "newton", subject: "physics", ncertClass: 11,
    chapter: "Laws of Motion",
    name: "Laws of Motion — Pulleys, Wedges, Lifts and Friction",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "collisions", subject: "physics", ncertClass: 11,
    chapter: "System of Particles · Centre of Mass",
    name: "Collisions — Air Track, Photogates and the Centre of Mass",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "capacitance", subject: "physics", ncertClass: 12,
    chapter: "Electrostatic Potential and Capacitance",
    name: "Capacitors — Dielectrics, Energy and the Pull on a Slab",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "gravitation", subject: "physics", ncertClass: 11,
    chapter: "Gravitation",
    name: "Gravitation — Orbits, the Inside of the Earth and Weighing G",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "fluids", subject: "physics", ncertClass: 11,
    chapter: "Mechanical Properties of Fluids",
    name: "Fluids — Pressure, Flow, Viscosity and Surface Tension",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "orbitals", subject: "chemistry", ncertClass: 11,
    chapter: "Structure of Atom",
    name: "Hydrogen Atomic Orbitals — Shape, Phase and Nodes",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "High yield" },
  { id: "substitution", subject: "chemistry", ncertClass: 12,
    chapter: "Haloalkanes & Haloarenes",
    name: "SN1 vs SN2 — Mechanism, Stereochemistry and Rate Law",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "bohr", subject: "chemistry", ncertClass: 11,
    chapter: "Structure of Atom",
    name: "Bohr Model & the Hydrogen Spectrum",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "elimination", subject: "chemistry", ncertClass: 12,
    chapter: "Haloalkanes & Haloarenes",
    name: "E1 vs E2 Elimination — Geometry, Saytzeff and Hofmann",
    exams: ["JEE Main", "JEE Advanced", "NEET UG"], weight: "Very high yield" },
  { id: "huckel", subject: "chemistry", ncertClass: 11,
    chapter: "Aromaticity & Molecular Orbitals",
    name: "Hückel MO Theory — Where 4n + 2 Actually Comes From",
    exams: ["JEE Advanced", "JEE Main"], weight: "Very high yield" },
  { id: "conformers", subject: "chemistry", ncertClass: 11,
    chapter: "Stereochemistry & Conformation",
    name: "Conformational Analysis — Newman Projections & the Ring Flip",
    exams: ["JEE Advanced", "JEE Main", "NEET UG"], weight: "High yield" },
  { id: "eas", subject: "chemistry", ncertClass: 11,
    chapter: "Aromatic Compounds",
    name: "Electrophilic Aromatic Substitution — Directing Effects from First Principles",
    exams: ["JEE Advanced", "JEE Main", "NEET UG"], weight: "Very high yield" },
  { id: "chirality", subject: "chemistry", ncertClass: 12,
    chapter: "Stereochemistry",
    name: "Chirality, CIP and the Polarimeter",
    exams: ["JEE Advanced", "JEE Main", "NEET UG"], weight: "Very high yield" },
  { id: "carbocation", subject: "chemistry", ncertClass: 11,
    chapter: "Hydrocarbons & Reaction Mechanisms",
    name: "Carbocations — Markovnikov, Hyperconjugation and Rearrangement",
    exams: ["JEE Advanced", "JEE Main", "NEET UG"], weight: "Very high yield" },
  { id: "ak-key", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "The Classification Key — Narrowing Eleven Phyla to One",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "ak-symmetry", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Body Symmetry — Counting the Planes",
    exams: ["NEET UG"], weight: "High yield" },
  { id: "ak-coelom", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Germ Layers and the Body Cavity",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "ak-canal", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Sponge Canal Systems — Following the Water",
    exams: ["NEET UG"], weight: "High yield" },
  { id: "ak-cnidaria", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Cnidaria — Nematocyst Discharge and Metagenesis",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "ak-wvs", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Water Vascular System — How a Starfish Walks",
    exams: ["NEET UG"], weight: "High yield" },
  { id: "ak-heart", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Vertebrate Heart — Two Chambers to Four",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "ak-chordata", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Chordate Characters and the Vertebrate Tree",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "ak-challenge", subject: "biology", ncertClass: 11,
    chapter: "Animal Kingdom",
    name: "Specimen Identification Challenge",
    exams: ["NEET UG"], weight: "Exam drill" },
  { id: "actionpotential", subject: "biology", ncertClass: 11,
    chapter: "Neural Control & Coordination",
    name: "Nerve Impulse — the Hodgkin–Huxley Action Potential",
    exams: ["NEET UG", "JEE Main"], weight: "Very high yield" },
  { id: "cardiac", subject: "biology", ncertClass: 11,
    chapter: "Body Fluids & Circulation",
    name: "The Cardiac Cycle — Pressure, Volume, Valves and the ECG",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "synapse", subject: "biology", ncertClass: 11,
    chapter: "Neural Control & Coordination",
    name: "The Synapse — Quantal Release, Summation and Drugs",
    exams: ["NEET UG"], weight: "Very high yield" },
  { id: "conduction", subject: "biology", ncertClass: 11,
    chapter: "Body Fluids & Circulation",
    name: "Cardiac Conduction System & Heart Block",
    exams: ["NEET UG"], weight: "High yield" },
];
